from common_data_sets.common.abstract_glue_table_mapping import AbstractGlueTableMapping
from pyspark.sql.types import StringType, StructField, StructType, DecimalType, TimestampType, DateType, \
    IntegerType, \
    BooleanType
from common_data_sets.common.configs import config


class Claims(AbstractGlueTableMapping):
    schema_name = config.CLAIMS_SCHEMA
    table_name = "claims"
    key_columns = ["sourcesystemid"]
    date_column = 'claiminvoicereceiveddate'
    metrics = ['incurredcurrencybilledamount', 'productcurrencypaymentamount', 'paymentcurrencypaymentamount',
               'allowedamount', 'discountamount', 'customershareamount']

    threshold = [{"prior_years": 1, "current_year_threshold": 5, "prior_year_threshold": 1, "prior_months": 1,
                  "current_month_threshold": 5, "prior_month_threshold": 2}]

    @property
    def schema(self):
        schema = StructType(
            [
                StructField('claimlineid', StringType(), True),
                StructField('originalclaiminvoiceid', StringType(), True),
                StructField('claimexternalinvoiceid', StringType(), True),
                StructField('claimexternalinvoicereference', StringType(), True),
                StructField('claimsubmissionid', StringType(), True),
                StructField('claiminvoiceid', StringType(), True),
                StructField('partnerclaimid', StringType(), True),
                StructField('legalentityid', StringType(), True),
                StructField('legalentityname', StringType(), True),
                StructField('lineofbusinessid', StringType(), True),
                StructField('lineofbusinessname', StringType(), True),
                StructField('edw_businessline', StringType(), True),
                StructField('edw_businesslinedesc', StringType(), True),
                StructField('edw_producttreekey', StringType(), True),
                StructField('edw_producttreedesc', StringType(), True),
                StructField('edw_businessbook', StringType(), True),
                StructField('edw_businessbookdesc', StringType(), True),
                StructField('segment', StringType(), True),
                StructField('market', StringType(), True),
                StructField('parentclientid', StringType(), True),
                StructField('clientid', StringType(), True),
                StructField('ancestorid', StringType(), True),
                StructField('clientlevel', IntegerType(), True),
                StructField('clientname', StringType(), True),
                StructField('internalindustrysector', StringType(), True),
                StructField("clientbusinesssegment", StringType(), True),
                StructField("claimsriskarrangement", StringType(), True),
                StructField('memberid', StringType(), True),
                StructField("dependentid", StringType(), True),
                StructField("clientstaffcategoryid", StringType(), True),
                StructField("clientstaffcategoryname", StringType(), True),
                StructField('formattedmemberid', StringType(), True),
                StructField('dateofbirth', DateType(), True),
                StructField('tds_claimage', IntegerType(), True),
                StructField('relationshiptypecode', StringType(), True),
                StructField('subscriberindicator', BooleanType(), True),
                StructField('familyunitid', StringType(), True),
                StructField('familyunittype', StringType(), True),
                StructField('clientpersonnelreferenceid', StringType(), True),
                StructField('gendercode', StringType(), True),
                StructField('customerid', StringType(), True),
                StructField('policyid', StringType(), True),
                StructField("policyname", StringType(), True),
                StructField('packageid', StringType(), True),
                StructField('packagename', StringType(), True),
                StructField('planname', StringType(), True),
                StructField('countryofresidencecode', StringType(), True),
                StructField('countryofresidence', StringType(), True),
                StructField('nationalitycode', StringType(), True),
                StructField('nationality', StringType(), True),
                StructField('productid', StringType(), True),
                StructField('productname', StringType(), True),
                StructField('benefitid', StringType(), True),
                StructField('benefitname', StringType(), True),
                StructField('networkusage', StringType(), True),
                StructField('admissiontypecode', StringType(), True),
                StructField('admissiontype', StringType(), True),
                StructField("lineofcover", StringType(), True),
                StructField('claiminvoicestatuslevel1', StringType(), True),
                StructField('claiminvoicestatuslevel2', StringType(), True),
                StructField('claiminvoicestatuslevel3', StringType(), True),
                StructField('claimlinestatuslevel1', StringType(), True),
                StructField('claimlinestatuslevel2', StringType(), True),
                StructField('claimlinestatuslevel3', StringType(), True),
                StructField('claimpaymentstatuslevel1', StringType(), True),
                StructField('claimpaymentstatuslevel2', StringType(), True),
                StructField('claimpaymentstatuslevel3', StringType(), True),
                StructField('incurredcountrycode', StringType(), True),
                StructField('incurredcountry', StringType(), True),
                StructField('claimlanguagecode', StringType(), True),
                StructField('internaldiagnosis', StringType(), True),
                StructField('internaldiagnosiscode', StringType(), True),
                StructField('icd9code', StringType(), True),
                StructField('icd9', StringType(), True),
                StructField('ccs_lv1_code', StringType(), True),
                StructField('ccs_lv1_desc', StringType(), True),
                StructField('ccs_lv2_code', StringType(), True),
                StructField('ccs_lv2_desc', StringType(), True),
                StructField('ccs_lv3_code', StringType(), True),
                StructField('ccs_lv3_desc', StringType(), True),
                StructField('cci_chronic', StringType(), True),
                StructField('icd10code', StringType(), True),
                StructField('icd10', StringType(), True),
                StructField('icd10codes_2024', StringType(), True),
                StructField('icd10_code_description', StringType(), True),
                StructField('ccsr_category_ip', StringType(), True),
                StructField('ccsr_category_description_ip', StringType(), True),
                StructField('ccsr_category_op', StringType(), True),
                StructField('ccsr_category_description_op', StringType(), True),
                StructField('ccsr_category_1', StringType(), True),
                StructField('ccsr_category_1_description', StringType(), True),
                StructField('ccsr_category_2', StringType(), True),
                StructField('ccsr_category_2_description', StringType(), True),
                StructField('ccsr_category_3', StringType(), True),
                StructField('ccsr_category_3_description', StringType(), True),
                StructField('icd10_chronic_indicator', StringType(), True),
                StructField('ccsr_body_system_abbreviation_2024', StringType(), True),
                StructField('icd_10_code_book_chapter_2024', StringType(), True),
                StructField('internalprocedurecode', StringType(), True),
                StructField('internalprocedure', StringType(), True),
                StructField('tds_casetype', StringType(), True),
                StructField('tds_casetypename', StringType(), True),
                StructField('reversal_flag', StringType(), True),
                StructField('servicecode', StringType(), True),
                StructField('service', StringType(), True),
                StructField('hcpcscode', StringType(), True),
                StructField('cdtcode', StringType(), True),
                StructField('cptcode', StringType(), True),
                StructField('cpt', StringType(), True),
                StructField('proceduretypecode', StringType(), True),
                StructField('proceduretype', StringType(), True),
                StructField('currentproceduralterminologymodifiercode', StringType(), True),
                StructField('currentproceduralterminologymodifier', StringType(), True),
                StructField('admissiondate', DateType(), True),
                StructField('dischargedate', DateType(), True),
                StructField('bednight', IntegerType(), True),
                StructField('placeofservice', StringType(), True),
                StructField('claimchannel', StringType(), True),
                StructField('servicefromdate', DateType(), True),
                StructField('servicetodate', DateType(), True),
                StructField('servicedate', DateType(), True),
                StructField('claimsubmissiondate', DateType(), True),
                StructField('claiminvoicereceiveddate', DateType(), True),
                StructField('paymentchannel', StringType(), True),
                StructField('paymentdate', DateType(), True),
                StructField('claimsettlementdate', DateType(), True),
                StructField('reporteddate', DateType(), True),
                StructField('paymentid', StringType(), True),
                StructField('originalpaymentid', StringType(), True),
                StructField('claimsettlementid', StringType(), True),
                StructField('externalpaymentreference', StringType(), True),
                StructField('checkid', StringType(), True),
                StructField('bankaccountinternalid', StringType(), True),
                StructField('bankcountry', StringType(), True),
                StructField('ibannumber', StringType(), True),
                StructField('bankaccountnumber', StringType(), True),
                StructField('unitquantitycount', IntegerType(), True),
                StructField('tds_paidto', StringType(), True),
                StructField('paymentrequestor', StringType(), True),
                StructField('productcurrencycode', StringType(), True),
                StructField('productcurrency', StringType(), True),
                StructField('productcurrencybilledamount', DecimalType(17, 2), True),
                StructField('incurredcurrencycode', StringType(), True),
                StructField('incurredcurrency', StringType(), True),
                StructField('incurredcurrencybilledamount', DecimalType(17, 2), True),
                StructField('tds_billedamountusd', DecimalType(17, 2), True),
                StructField('productcurrencypaymentamount', DecimalType(17, 2), True),
                StructField('paymentcurrencycode', StringType(), True),
                StructField('paymentcurrency', StringType(), True),
                StructField('paymentcurrencypaymentamount', DecimalType(17, 2), True),
                StructField('tds_paymentamountusd', DecimalType(17, 2), True),
                StructField('networkclientfeeamount', DecimalType(17, 2), True),
                StructField('tds_networkclientfeeamountusd', DecimalType(17, 2), True),
                StructField('customershareamount', DecimalType(17, 2), True),
                StructField('tds_customershareamountusd', DecimalType(17, 2), True),
                StructField('deniedamount', DecimalType(17, 2), True),
                StructField('tds_deniedamountusd', DecimalType(17, 2), True),
                StructField('copaymentamount', DecimalType(17, 2), True),
                StructField('tds_copaymentamountusd', DecimalType(17, 2), True),
                StructField('tds_copayamountincurredcurrency', DecimalType(17, 2), True),
                StructField('allowedamount', DecimalType(17, 2), True),
                StructField('tds_allowedamountusd', DecimalType(17, 2), True),
                StructField('tds_allowedamountincurredcurrency', DecimalType(17, 2), True),
                StructField('deductibleamount', DecimalType(17, 2), True),
                StructField('tds_deductibleamountusd', DecimalType(17, 2), True),
                StructField('tds_deductibleamountincurredcurrency', DecimalType(17, 2), True),
                StructField('networkfeeamount', DecimalType(17, 2), True),
                StructField('tds_networkfeeamountusd', DecimalType(17, 2), True),
                StructField('tds_grossamountusd', DecimalType(17, 2), True),
                StructField('taxamount', DecimalType(17, 2), True),
                StructField('noncompliancepenaltyamount', DecimalType(17, 2), True),
                StructField('notpayableamount', DecimalType(17, 2), True),
                StructField('tds_notpayableamountusd', DecimalType(17, 2), True),
                StructField('tds_notcoveredamountincurredcurrency', DecimalType(17, 2), True),
                StructField('outofpocketbreachedamount', DecimalType(17, 2), True),
                StructField('reimbursementlimitreductionamount', DecimalType(17, 2), True),
                StructField('discountamount', DecimalType(17, 2), True),
                StructField('tds_discountamountusd', DecimalType(17, 2), True),
                StructField('tds_discountamountincurredcurrency', DecimalType(17, 2), True),
                StructField('discounttypecode', StringType(), True),
                StructField('otherinsureramount', DecimalType(17, 2), True),
                StructField('coinsuranceamount', DecimalType(17, 2), True),
                StructField('recoveredamount', DecimalType(17, 2), True),
                StructField('costplusfeeamount', DecimalType(17, 2), True),
                StructField('savingclientfeeamount', DecimalType(17, 2), True),
                StructField('deniedreasoncode', StringType(), True),
                StructField('deniedreason', StringType(), True),
                StructField('deniedreasonuscode', StringType(), True),
                StructField('reasonnotcovereduscode', StringType(), True),
                StructField('reasonnotcoveredus', StringType(), True),
                StructField('reimbursementlimitreductionreasoncode', StringType(), True),
                StructField('reimbursementlimitreductionreason', StringType(), True),
                StructField('reasonableandcustomaryreductionreasoncode', StringType(), True),
                StructField('reasonableandcustomaryreductionreason', StringType(), True),
                StructField('cignalinkspartnerindicator', BooleanType(), True),
                StructField('masterpartnerid', StringType(), True),
                StructField('masterpartnername', StringType(), True),
                StructField('partnerid', StringType(), True),
                StructField('partnername', StringType(), True),
                StructField('renderingproviderid', StringType(), True),
                StructField('billingproviderid', StringType(), True),
                StructField('billingprovidertypecode', StringType(), True),
                StructField('billingprovidertype', StringType(), True),
                StructField('billingproviderspecialty', StringType(), True),
                StructField('billingprovidercompanyname', StringType(), True),
                StructField('billingmasterproviderid', StringType(), True),
                StructField('billingprovidergroupcode', StringType(), True),
                StructField('billingprovidergroup', StringType(), True),
                StructField('hospitalrevenuecode', StringType(), True),
                StructField('hospitalrevenue', StringType(), True),
                StructField('paymentcurrencytotalpaymentamount', DecimalType(17, 2), True),
                StructField('sourcesystemname', StringType(), True),
                StructField('sourcesystemid', StringType(), True),
                StructField('sysbatchdttm', TimestampType(), True)
            ]
        )

        return schema


def claims(*args, **kwargs):
    clm = Claims()
    clm.initialize_table(**kwargs)
    return clm
